#!/bin/bash
sudo apt install -y apache2
sudo apt install -y php7.4 php7.4-mysql php-common php7.4-cli php7.4-json php7.4-common php7.4-opcache libapache2-mod-php7.4
sudo systemctl restart apache2
sudo apt install -y mariadb-server mariadb-client
sudo snap install core; sudo snap refresh core
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo mysql_secure_installation
